API:
    token: <replace-with-your-api-key>
export_options:
    export_path: /app/csv/
    timezone: Europe/London
    filename:
    csv_options:
        export_inactive_items: false
    export_profiles:
    sync_delay_in_seconds: 900
    media_sync_offset_in_seconds:
